version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "google-sheets-updater"
s3_bucket = <bucket-name>
s3_prefix = "google-sheets-updater"
region = "ap-south-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "SpreadsheetId=\"<SpreadsheetId>\" GoogleClientEmail=\"<Google Cloud service account email>\" GooglePrivateKey=\"<GCP private key>\""
image_repositories = []
resolve_s3 = true
